import cv2
import detect
import preProcess

img=cv2.imread('./test_img/img15.png')
rect_list,ROI=detect.detect_target(img)
detect.get_numberShot(img,rect_list,ROI)
cv2.waitKey(0)
img=cv2.imread('./test_img/img22.png')
rect_list,ROI=detect.detect_target(img)
detect.get_numberShot(img,rect_list,ROI)
cv2.waitKey(0)
img=cv2.imread('./test_img/img32.png')
rect_list,ROI=detect.detect_target(img)
detect.get_numberShot(img,rect_list,ROI)
cv2.waitKey(0)
img=cv2.imread('./test_img/img49.png')
rect_list,ROI=detect.detect_target(img)
detect.get_numberShot(img,rect_list,ROI)
cv2.waitKey(0)
img=cv2.imread('./test_img/img44.png')
rect_list,ROI=detect.detect_target(img)
detect.get_numberShot(img,rect_list,ROI)
cv2.waitKey(0)
img=cv2.imread('./test_img/img58.png')
rect_list,ROI=detect.detect_target(img)
detect.get_numberShot(img,rect_list,ROI)
cv2.waitKey(0)
img=cv2.imread('./test_img/img69.png')
rect_list,ROI=detect.detect_target(img)
detect.get_numberShot(img,rect_list,ROI)
cv2.waitKey(0)
img=cv2.imread('./test_img/img72.png')
rect_list,ROI=detect.detect_target(img)
detect.get_numberShot(img,rect_list,ROI)
cv2.waitKey(0)

